Update package-lock.json
MicroFocus/microfocus.github.io pull request #52
Opened 2022-10-27 04:49 UTC by vishalkumar-barnwal

https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=582211

2022-10-27 04:55 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://jenkins.swinfra.net/job/SEPG/job/MicroFocus/job/MicroFocus~microfocus.github.io~US582211~CI

2022-10-27 05:05 UTC, buildmachine-sou-jenkins2 commented
The Documentation QA site for this branch has been built:
https://pages.github.houston.softwaregrp.net/sepg-docs-qa/MicroFocus_CI_microfocus.github.io_US582211

2022-10-27 12:04 UTC, vishalkumar-barnwal commented
@dermot-hardy I tried building changes suggested by dependabot in below PRs in jenkins, but they are failing with some error but at the same time I tried creating this branch and changed as per the dependabot suggestions and it's building successfully. I'm checking those errors currently but can we merge those suggestions with this PR only?

**Eventsource and Lodash PR created by dependabot**:
- eventsource https://github.com/MicroFocus/microfocus.github.io/pull/46
- lodash https://github.com/MicroFocus/microfocus.github.io/pull/29

2022-11-01 10:28 UTC, andyreidz requested changes
Can you correct the PR title to reflect the work done?
Can you link to the original PR so we can see the relationship between then?

2022-11-02 12:27 UTC, closed without merging